objects:
  role:
    configure:
      description: configures essential parts of OPNsense
      name: configure
      version_added: 1.0.0
plugins:
  become: {}
  cache: {}
  callback: {}
  cliconf: {}
  connection: {}
  filter: {}
  httpapi: {}
  inventory: {}
  lookup: {}
  module: {}
  netconf: {}
  shell: {}
  strategy: {}
  test: {}
  vars: {}
version: 1.1.1
