---
dependencies: []

galaxy_info:
  role_name: configure
  author: Nils Ost (@nils-ost)
  description: configures essential parts of OPNsense
  license: GPL-3.0-or-later
  min_ansible_version: 2.13.9
  galaxy_tags:
    - opnsense
    - router
    - firewall
    - configure
