---
# this is just printed as a helper after VLANs are configured to remember user for manual interfaces config
opnsense_interfaces: []

# this is just printed as a helper after gateways are configured to remember user for manual gateway group config
opnsense_gateway_groups: []

opnsense_vlans: {}

opnsense_gateways: {}

opnsense_dhcp: {}

opnsense_dhcp_subnets: {}

opnsense_dhcp_reservations: {}

opnsense_aliases: {}

opnsense_nat_outbound: {}

opnsense_shaper_pipes: {}

opnsense_shaper_queues: {}

opnsense_shaper_rules: {}

opnsense_rules: {}

opnsense_tailscale_advertised_routes: {}
